In [9]:
import numpy as np
#state = 1,2,3

transition_matrix = np.array([[0.1,0.1 ,0.3],
                              [0.6,0.25,0.5],
                              [0.3,0.65,0.2]])
for i in range(10):
    new_matrix = np.dot(transition_matrix,transition_matrix)
    transition_matrix = new_matrix
print(transition_matrix)

[[0.18092105 0.18092105 0.18092105]
 [0.41447368 0.41447368 0.41447368]
 [0.40460526 0.40460526 0.40460526]]
